# Generated by Django 2.2.7 on 2019-12-06 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类目名称')),
            ],
            options={
                'verbose_name_plural': '商品类目',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类目属性')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.Categories', verbose_name='类目')),
            ],
            options={
                'verbose_name_plural': '商品类目属性',
                'db_table': 'categoryproperty',
            },
        ),
        migrations.CreateModel(
            name='CategoryValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类目属性值')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.CategoryProperty', verbose_name='类目属性')),
            ],
            options={
                'verbose_name_plural': '商品类目属性值',
                'db_table': 'categoryvalue',
            },
        ),
        migrations.CreateModel(
            name='ExhaustedAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('describe', models.CharField(max_length=100, verbose_name='商品描述')),
                ('img', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.Categories', verbose_name='类目')),
            ],
            options={
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('first_name', models.CharField(max_length=10, verbose_name='姓')),
                ('last_name', models.CharField(max_length=10, verbose_name='名')),
                ('describe', models.CharField(max_length=50, verbose_name='个人简介')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('phone_number', models.IntegerField(verbose_name='电话号码')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('num', models.IntegerField(verbose_name='库存数量')),
                ('attr', models.ManyToManyField(through='admin1.ExhaustedAttr', to='admin1.CategoryProperty')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.Goods', verbose_name='商品id')),
            ],
            options={
                'verbose_name_plural': '库存',
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='Shopcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.Goods', verbose_name='商品id')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'shopcar',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='订单状态')),
                ('phone', models.IntegerField(verbose_name='电话号码')),
                ('money', models.IntegerField(verbose_name='订单金额')),
                ('pay', models.IntegerField(verbose_name='支付方式')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单信息',
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='exhaustedattr',
            name='Stocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.Stocks'),
        ),
        migrations.AddField(
            model_name='exhaustedattr',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.CategoryProperty'),
        ),
        migrations.AddField(
            model_name='exhaustedattr',
            name='attrchoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.CategoryValue', verbose_name='规格选项'),
        ),
        migrations.CreateModel(
            name='Dindan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.Goods', verbose_name='商品名称')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单',
                'db_table': 'dindan',
            },
        ),
    ]
