# Generated by Django 2.2.7 on 2019-12-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_auto_20191206_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryvalue',
            old_name='pid',
            new_name='value',
        ),
    ]
